POST http://localhost:3001/api/notes 
content-type: application/json

{
    "content": "Hola Jackson Zambrano",
    "important": true,
    "userId": "6058b6c8b027700719eb6a41"
}

###

POST http://localhost:3001/api/notes 
content-type: application/json

{
}